### ISSUE TITLE
Error "No module named setuptools_ext" when installing egg v0.8.1

### ISSUE THREAD

**Issue by jbbarth** [botify-labs/judyz#4]
It seems I cannot install the latest version:

```
Collecting judyz-cffi>=0.6.0 (from xxxxxxx==0.15.2->-r requirements/production.txt (line 8))
  Downloading http://xxxxxxx/packages/judyz-cffi/download/15367/judyz-cffi-0.8.1.tar.gz
    Complete output from command python setup.py egg_info:

    Installed /tmp/pip-build-4Smw1n/judyz-cffi/.eggs/cffi-1.1.2-py2.7-linux-x86_64.egg
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-4Smw1n/judyz-cffi/setup.py", line 14, in <module>
        install_requires=["cffi>=1.0.0"],
      File "/usr/lib/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/local/lib/python2.7/dist-packages/setuptools/dist.py", line 272, in __init__
        _Distribution.__init__(self,attrs)
      File "/usr/lib/python2.7/distutils/dist.py", line 287, in __init__
        self.finalize_options()
      File "/usr/local/lib/python2.7/dist-packages/setuptools/dist.py", line 327, in finalize_options
        ep.load()(self, ep.name, value)
      File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2355, in load
        return self.resolve()
      File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2361, in resolve
        module = __import__(self.module_name, fromlist=['__name__'], level=0)
    ImportError: No module named setuptools_ext
```

I can provide you more informations if needed

**Comment by ybastide** [comment]
pip stupidity.

One must upgrade cffi first. The Dockerfile does it in order (like for the other dependencies)

**Comment by jbbarth** [comment]
Ok, will have a look. I hate pip so much :(

**Comment by jbbarth** [comment]
Actually we were locking `cffi==0.9.2` in our other project, which, combined with pip mediocrity, resulted in the error above (judyz install was using cffi 0.9.2 instead of 1.0.0+). Closing, thanks :)
